const form = document.querySelector('#contact-form');
const contactsBody = document.querySelector('#contacts-body');
const emptyState = document.querySelector('#empty-state');
const appMessage = document.querySelector('#app-message');
const searchInput = document.querySelector('#search-input');
const sortSelect = document.querySelector('#sort-select');
let contacts = [];
let editingId = null;

const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
const formatDate = (value) => new Date(`${value}Z`).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' });
function showMessage(message, type = 'success') { appMessage.textContent = message; appMessage.className = `feedback visible ${type}`; window.clearTimeout(showMessage.timeout); showMessage.timeout = window.setTimeout(() => { appMessage.className = 'feedback'; }, 4500); }
function formData() { return { nome: form.nome.value, email: form.email.value, telefone: form.telefone.value, assunto: form.assunto.value, mensagem: form.mensagem.value, newsletter: form.newsletter.checked }; }
function renderContacts() {
  const search = searchInput.value.trim().toLocaleLowerCase();
  const sort = sortSelect.value;
  const visible = contacts.filter((contact) => contact.nome.toLocaleLowerCase().includes(search)).sort((a, b) => sort === 'name-asc' ? a.nome.localeCompare(b.nome) : sort === 'name-desc' ? b.nome.localeCompare(a.nome) : sort === 'id-asc' ? a.id - b.id : b.id - a.id);
  contactsBody.innerHTML = visible.map((contact) => `<tr><td>#${contact.id}</td><td><span class="contact-name">${escapeHtml(contact.nome)}</span><br><span>${escapeHtml(contact.email)}</span></td><td>${escapeHtml(contact.telefone)}</td><td>${escapeHtml(contact.assunto)}</td><td class="message-cell" title="${escapeHtml(contact.mensagem)}">${escapeHtml(contact.mensagem)}</td><td>${contact.newsletter ? '<span class="newsletter-yes">&#10003;</span>' : '<span>-</span>'}</td><td>${formatDate(contact.recebidoEm)}</td><td><div class="actions"><button class="action-button" data-action="edit" data-id="${contact.id}" type="button">Editar</button><button class="action-button delete" data-action="delete" data-id="${contact.id}" type="button">Excluir</button></div></td></tr>`).join('');
  emptyState.classList.toggle('hidden', visible.length !== 0);
  document.querySelector('#contact-count').textContent = contacts.length;
  document.querySelector('#record-badge').textContent = `${contacts.length} ${contacts.length === 1 ? 'registro' : 'registros'}`;
  document.querySelector('#last-update').textContent = new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' });
}
async function loadContacts() {
  const response = await fetch('/dados');
  if (response.status === 401) return window.location.href = '/login.html';
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Falha ao carregar contatos.');
  contacts = data; renderContacts();
}
function resetForm() { form.reset(); editingId = null; document.querySelector('#contact-id').value = ''; document.querySelector('#form-title').textContent = 'Adicionar contato'; document.querySelector('#submit-button').innerHTML = 'Enviar contato <span aria-hidden="true">&#8594;</span>'; document.querySelector('#cancel-edit').classList.add('hidden'); }
function beginEdit(contact) { editingId = contact.id; form.nome.value = contact.nome; form.email.value = contact.email; form.telefone.value = contact.telefone; form.assunto.value = contact.assunto; form.mensagem.value = contact.mensagem; form.newsletter.checked = Boolean(contact.newsletter); document.querySelector('#form-title').textContent = 'Editar contato'; document.querySelector('#submit-button').innerHTML = 'Atualizar contato <span aria-hidden="true">&#8594;</span>'; document.querySelector('#cancel-edit').classList.remove('hidden'); document.querySelector('#nome').focus(); }
form.addEventListener('submit', async (event) => { event.preventDefault(); const payload = formData(); const method = editingId ? 'PUT' : 'POST'; const url = editingId ? `/api/contato/${editingId}` : '/api/contato'; const button = document.querySelector('#submit-button'); button.disabled = true; try { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível salvar.'); await loadContacts(); resetForm(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } finally { button.disabled = false; } });
contactsBody.addEventListener('click', async (event) => { const button = event.target.closest('button[data-action]'); if (!button) return; const id = Number(button.dataset.id); const contact = contacts.find((item) => item.id === id); if (button.dataset.action === 'edit' && contact) return beginEdit(contact); if (button.dataset.action === 'delete' && contact && window.confirm(`Excluir o contato de ${contact.nome}?`)) { try { const response = await fetch(`/api/contato/${id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível excluir.'); await loadContacts(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } } });
searchInput.addEventListener('input', renderContacts); sortSelect.addEventListener('change', renderContacts); document.querySelector('#cancel-edit').addEventListener('click', resetForm); document.querySelector('#logout-button').addEventListener('click', async () => { await fetch('/api/logout', { method: 'POST' }); window.location.href = '/login.html'; }); document.querySelector('#today-label').textContent = new Date().toLocaleDateString('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' });
loadContacts().catch((error) => showMessage(error.message, 'error'));

const quoteForm = document.querySelector('#quote-form');
const quotesBody = document.querySelector('#quotes-body');
const quotesEmptyState = document.querySelector('#quotes-empty-state');
const quoteSearchInput = document.querySelector('#quote-search-input');
const quoteStatusFilter = document.querySelector('#quote-status-filter');
let quotes = [];
let editingQuoteId = null;

const quoteField = (name) => quoteForm.elements[name];
const money = (value) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const quotePayload = () => ({ cliente: quoteField('cliente').value, telefone: quoteField('telefone').value, email: quoteField('email').value, produto: quoteField('produto').value, largura: quoteField('largura').value, altura: quoteField('altura').value, quantidade: quoteField('quantidade').value, tipoVidro: quoteField('tipoVidro').value, espessura: quoteField('espessura').value, acabamento: quoteField('acabamento').value, acessorios: quoteField('acessorios').value, precoVidroM2: quoteField('precoVidroM2').value, valorFerragens: quoteField('valorFerragens').value, valorInstalacao: quoteField('valorInstalacao').value, desconto: quoteField('desconto').value, observacoes: quoteField('observacoes').value, status: quoteField('status').value });
function updateQuoteCalculation() { const payload = quotePayload(); const area = (Number(payload.largura) || 0) * (Number(payload.altura) || 0); const areaTotal = area * (Number(payload.quantidade) || 0); const valorVidro = areaTotal * (Number(payload.precoVidroM2) || 0); const subtotal = valorVidro + (Number(payload.valorFerragens) || 0) + (Number(payload.valorInstalacao) || 0); const final = subtotal - (Number(payload.desconto) || 0); document.querySelector('#quote-area-total').textContent = `${areaTotal.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} m²`; document.querySelector('#quote-valor-vidro').textContent = money(valorVidro); document.querySelector('#quote-subtotal').textContent = money(subtotal); document.querySelector('#quote-valor-final').textContent = money(Math.max(0, final)); }
function renderQuotes() { const search = quoteSearchInput.value.trim().toLocaleLowerCase(); const status = quoteStatusFilter.value; const visible = quotes.filter((quote) => (!search || `${quote.numero} ${quote.cliente} ${quote.produto}`.toLocaleLowerCase().includes(search)) && (!status || quote.status === status)); quotesBody.innerHTML = visible.map((quote) => `<tr><td><strong>${escapeHtml(quote.numero)}</strong></td><td><span class="contact-name">${escapeHtml(quote.cliente)}</span><br><span>${escapeHtml(quote.telefone)}</span></td><td>${escapeHtml(quote.produto)}</td><td>${Number(quote.areaTotal).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} m²</td><td><strong>${money(quote.valorFinal)}</strong></td><td><span class="status-badge status-${quote.status.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s/g, '-')}">${escapeHtml(quote.status)}</span></td><td>${formatDate(quote.criadoEm)}</td><td><div class="actions"><button class="action-button" data-quote-action="edit" data-id="${quote.id}" type="button">Editar</button><button class="action-button delete" data-quote-action="delete" data-id="${quote.id}" type="button">Excluir</button></div></td></tr>`).join(''); quotesEmptyState.classList.toggle('hidden', visible.length !== 0); document.querySelector('#quote-record-badge').textContent = `${quotes.length} ${quotes.length === 1 ? 'registro' : 'registros'}`; }
async function loadQuotes() { const response = await fetch('/api/orcamentos'); if (response.status === 401) return window.location.href = '/login.html'; const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Falha ao carregar orçamentos.'); quotes = data; renderQuotes(); }
function resetQuoteForm() { quoteForm.reset(); quoteField('quantidade').value = 1; quoteField('precoVidroM2').value = 0; quoteField('valorFerragens').value = 0; quoteField('valorInstalacao').value = 0; quoteField('desconto').value = 0; editingQuoteId = null; document.querySelector('#quote-form-title').textContent = 'Criar orçamento'; document.querySelector('#quote-submit-button').innerHTML = 'Salvar orçamento <span aria-hidden="true">&#8594;</span>'; document.querySelector('#cancel-quote-edit').classList.add('hidden'); updateQuoteCalculation(); }
function beginQuoteEdit(quote) { editingQuoteId = quote.id; Object.keys(quotePayload()).forEach((key) => { if (quoteField(key)) quoteField(key).value = quote[key] ?? ''; }); document.querySelector('#quote-form-title').textContent = 'Editar orçamento'; document.querySelector('#quote-submit-button').innerHTML = 'Atualizar orçamento <span aria-hidden="true">&#8594;</span>'; document.querySelector('#cancel-quote-edit').classList.remove('hidden'); updateQuoteCalculation(); document.querySelector('#quote-cliente').focus(); }
quoteForm.addEventListener('input', updateQuoteCalculation);
quoteForm.addEventListener('submit', async (event) => { event.preventDefault(); const method = editingQuoteId ? 'PUT' : 'POST'; const url = editingQuoteId ? `/api/orcamentos/${editingQuoteId}` : '/api/orcamentos'; const button = document.querySelector('#quote-submit-button'); button.disabled = true; try { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(quotePayload()) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível salvar o orçamento.'); await loadQuotes(); resetQuoteForm(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } finally { button.disabled = false; } });
quotesBody.addEventListener('click', async (event) => { const button = event.target.closest('button[data-quote-action]'); if (!button) return; const id = Number(button.dataset.id); const quote = quotes.find((item) => item.id === id); if (button.dataset.quoteAction === 'edit' && quote) return beginQuoteEdit(quote); if (button.dataset.quoteAction === 'delete' && quote && window.confirm(`Excluir o orçamento ${quote.numero}?`)) { try { const response = await fetch(`/api/orcamentos/${id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível excluir.'); await loadQuotes(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } } });
quoteSearchInput.addEventListener('input', renderQuotes); quoteStatusFilter.addEventListener('change', renderQuotes); document.querySelector('#cancel-quote-edit').addEventListener('click', resetQuoteForm); updateQuoteCalculation(); loadQuotes().catch((error) => showMessage(error.message, 'error'));
