const form = document.querySelector('#contact-form');
const contactsBody = document.querySelector('#contacts-body');
const emptyState = document.querySelector('#empty-state');
const appMessage = document.querySelector('#app-message');
const searchInput = document.querySelector('#search-input');
const sortSelect = document.querySelector('#sort-select');
let contacts = [];
let editingId = null;

const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
const formatDate = (value) => new Date(`${value}Z`).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' });
function showMessage(message, type = 'success') { appMessage.textContent = message; appMessage.className = `feedback visible ${type}`; window.clearTimeout(showMessage.timeout); showMessage.timeout = window.setTimeout(() => { appMessage.className = 'feedback'; }, 4500); }
function formData() { return { nome: form.nome.value, email: form.email.value, telefone: form.telefone.value, assunto: form.assunto.value, mensagem: form.mensagem.value, newsletter: form.newsletter.checked }; }
function renderContacts() {
  const search = searchInput.value.trim().toLocaleLowerCase();
  const sort = sortSelect.value;
  const visible = contacts.filter((contact) => contact.nome.toLocaleLowerCase().includes(search)).sort((a, b) => sort === 'name-asc' ? a.nome.localeCompare(b.nome) : sort === 'name-desc' ? b.nome.localeCompare(a.nome) : sort === 'id-asc' ? a.id - b.id : b.id - a.id);
  contactsBody.innerHTML = visible.map((contact) => `<tr><td>#${contact.id}</td><td><span class="contact-name">${escapeHtml(contact.nome)}</span><br><span>${escapeHtml(contact.email)}</span></td><td>${escapeHtml(contact.telefone)}</td><td>${escapeHtml(contact.assunto)}</td><td class="message-cell" title="${escapeHtml(contact.mensagem)}">${escapeHtml(contact.mensagem)}</td><td>${contact.newsletter ? '<span class="newsletter-yes">&#10003;</span>' : '<span>-</span>'}</td><td>${formatDate(contact.recebidoEm)}</td><td><div class="actions"><button class="action-button" data-action="edit" data-id="${contact.id}" type="button">Editar</button><button class="action-button delete" data-action="delete" data-id="${contact.id}" type="button">Excluir</button></div></td></tr>`).join('');
  emptyState.classList.toggle('hidden', visible.length !== 0);
  document.querySelector('#contact-count').textContent = contacts.length;
  document.querySelector('#record-badge').textContent = `${contacts.length} ${contacts.length === 1 ? 'registro' : 'registros'}`;
  document.querySelector('#last-update').textContent = new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' });
}
async function loadContacts() {
  const response = await fetch('/dados');
  if (response.status === 401) return window.location.href = '/login.html';
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Falha ao carregar contatos.');
  contacts = data; renderContacts();
}
function resetForm() { form.reset(); editingId = null; document.querySelector('#contact-id').value = ''; document.querySelector('#form-title').textContent = 'Adicionar contato'; document.querySelector('#submit-button').innerHTML = 'Enviar contato <span aria-hidden="true">&#8594;</span>'; document.querySelector('#cancel-edit').classList.add('hidden'); }
function beginEdit(contact) { editingId = contact.id; form.nome.value = contact.nome; form.email.value = contact.email; form.telefone.value = contact.telefone; form.assunto.value = contact.assunto; form.mensagem.value = contact.mensagem; form.newsletter.checked = Boolean(contact.newsletter); document.querySelector('#form-title').textContent = 'Editar contato'; document.querySelector('#submit-button').innerHTML = 'Atualizar contato <span aria-hidden="true">&#8594;</span>'; document.querySelector('#cancel-edit').classList.remove('hidden'); document.querySelector('#nome').focus(); }
form.addEventListener('submit', async (event) => { event.preventDefault(); const payload = formData(); const method = editingId ? 'PUT' : 'POST'; const url = editingId ? `/api/contato/${editingId}` : '/api/contato'; const button = document.querySelector('#submit-button'); button.disabled = true; try { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível salvar.'); await loadContacts(); resetForm(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } finally { button.disabled = false; } });
contactsBody.addEventListener('click', async (event) => { const button = event.target.closest('button[data-action]'); if (!button) return; const id = Number(button.dataset.id); const contact = contacts.find((item) => item.id === id); if (button.dataset.action === 'edit' && contact) return beginEdit(contact); if (button.dataset.action === 'delete' && contact && window.confirm(`Excluir o contato de ${contact.nome}?`)) { try { const response = await fetch(`/api/contato/${id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível excluir.'); await loadContacts(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } } });
searchInput.addEventListener('input', renderContacts); sortSelect.addEventListener('change', renderContacts); document.querySelector('#cancel-edit').addEventListener('click', resetForm); document.querySelector('#logout-button').addEventListener('click', async () => { await fetch('/api/logout', { method: 'POST' }); window.location.href = '/login.html'; }); document.querySelector('#today-label').textContent = new Date().toLocaleDateString('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' });
loadContacts().catch((error) => showMessage(error.message, 'error'));

const quoteForm = document.querySelector('#quote-form');
const quotesBody = document.querySelector('#quotes-body');
const quotesEmptyState = document.querySelector('#quotes-empty-state');
const quoteSearchInput = document.querySelector('#quote-search-input');
const quoteStatusFilter = document.querySelector('#quote-status-filter');
const quoteField = (name) => quoteForm.elements[name];
const money = (value) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
let quotes = [];
let products = [];
let clients = [];
let quoteItems = [];
let editingQuoteId = null;
function quoteTotals() { const productsTotal = quoteItems.reduce((total, item) => total + item.subtotal, 0); const installation = Number(quoteField('instalacao').value) || 0; const labor = Number(quoteField('maoObra').value) || 0; const travel = Number(quoteField('deslocamento').value) || 0; const discount = Number(quoteField('desconto').value) || 0; const additions = Number(quoteField('acrescimos').value) || 0; return { productsTotal, subtotal: productsTotal + labor + installation + travel, installation, discount, total: productsTotal + labor + installation + travel - discount + additions }; }
function renderItems() { const body = document.querySelector('#quote-items-body'); const empty = document.querySelector('#quote-items-empty'); body.innerHTML = quoteItems.map((item, index) => `<tr><td><strong>${escapeHtml(item.descricao)}</strong>${item.largura && item.altura ? `<br><small>${item.largura.toFixed(2)} m x ${item.altura.toFixed(2)} m</small>` : ''}</td><td>${(item.area * item.quantidade).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} m²</td><td>${item.quantidade}</td><td>${item.unidade}</td><td>${money(item.valorUnitario)}</td><td><strong>${money(item.subtotal)}</strong></td><td><button class="action-button delete" type="button" data-remove-item="${index}">Remover</button></td></tr>`).join(''); empty.classList.toggle('hidden', quoteItems.length > 0); const totals = quoteTotals(); document.querySelector('#quote-subtotal').textContent = money(totals.subtotal); document.querySelector('#quote-discount-total').textContent = money(totals.discount); document.querySelector('#quote-install-total').textContent = money(totals.installation); document.querySelector('#quote-valor-final').textContent = money(Math.max(0, totals.total)); }
function fillClients() { quoteField('clienteId').innerHTML = '<option value="">Selecione um cliente</option>' + clients.map((client) => `<option value="${client.id}">${escapeHtml(client.nome)}</option>`).join(''); }
function fillProducts() { document.querySelector('#item-product').innerHTML = '<option value="">Selecione um produto do catálogo</option>' + products.filter((product) => product.ativo).map((product) => `<option value="${product.id}">${escapeHtml(product.nome)} - ${money(product.preco)}/${product.unidade}</option>`).join(''); }
async function api(url, options) { if (url === '/api/produtos' && (!options || !options.method || options.method === 'GET')) url = '/api/admin/produtos'; const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Operação não realizada.'); return data; }
const companyFields = ['razaoSocial', 'nomeFantasia', 'cnpj', 'telefone', 'whatsapp', 'email', 'endereco', 'cep', 'cidade', 'estado', 'logo'];
function setupCompanyForm() { document.querySelector('#company-form').innerHTML = companyFields.map((field) => `<div class="field${field === 'endereco' || field === 'logo' ? ' field-wide' : ''}"><label for="company-${field}">${field.replace(/([A-Z])/g, ' $1')}</label><input id="company-${field}" name="${field}" ${field === 'email' ? 'type="email"' : ''}></div>`).join('') + '<button class="button button-primary" type="submit">Salvar dados da empresa</button>'; }
const clientFields = ['nome', 'documento', 'telefone', 'whatsapp', 'email', 'endereco', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'cep'];
function setupClientForm() { document.querySelector('#client-form').innerHTML = clientFields.map((field) => `<input name="${field}" placeholder="${field === 'nome' ? 'Nome/Razão social' : field}">
`).join('') + '<button class="button button-primary" type="submit">Cadastrar cliente</button>'; }
function setupCategoryForm() { document.querySelector('#admin-products').insertAdjacentHTML('afterbegin', '<form id="category-form" class="inline-form category-form"><input name="nome" placeholder="Nova categoria" required><button class="button button-ghost" type="submit">Cadastrar categoria</button><select id="category-edit-select"><option value="">Editar categoria...</option></select><button id="category-edit-button" class="button button-ghost" type="button">Renomear</button></form>'); }
function setupProductFilters() { document.querySelector('#product-form').insertAdjacentHTML('beforebegin', '<div class="product-filters"><input id="product-search" type="search" placeholder="Pesquisar produtos" aria-label="Pesquisar produtos"><select id="product-category-filter" aria-label="Filtrar produtos por categoria"><option value="">Todas as categorias</option></select></div>'); document.querySelector('#products-body').closest('table').querySelector('thead tr').insertAdjacentHTML('beforeend', '<th>Ações</th>'); const price = document.querySelector('#product-form input[name="preco"]'); price.type = 'text'; price.inputMode = 'decimal'; price.placeholder = 'R$ 0,00'; price.addEventListener('focus', () => { price.value = price.value.replace(/R\$|\s/g, '').replace(/\./g, '').replace(',', '.'); }); price.addEventListener('blur', () => { const value = Number(price.value.replace(/\./g, '').replace(',', '.')); if (Number.isFinite(value)) price.value = value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }); }
function renderAdminProducts() { const search = document.querySelector('#product-search').value.trim().toLocaleLowerCase(); const category = document.querySelector('#product-category-filter').value; const visible = products.filter((product) => (!search || `${product.nome} ${product.referencia || ''}`.toLocaleLowerCase().includes(search)) && (!category || product.categoria === category)); document.querySelector('#products-body').innerHTML = visible.map((product) => `<tr><td>${escapeHtml(product.nome)}</td><td>${escapeHtml(product.categoria)}</td><td>${product.unidade}</td><td>${money(product.preco)}</td><td><span class="status-badge ${product.ativo ? 'status-aprovado' : 'status-cancelado'}">${product.ativo ? 'Ativo' : 'Inativo'}</span></td><td><div class="actions"><button class="action-button" data-product-action="edit" data-id="${product.id}" type="button">Editar</button><button class="action-button" data-product-action="toggle" data-id="${product.id}" type="button">${product.ativo ? 'Desativar' : 'Ativar'}</button><button class="action-button delete" data-product-action="delete" data-id="${product.id}" type="button">Excluir</button></div></td></tr>`).join(''); }
async function loadAdminData() { [products, clients] = await Promise.all([api('/api/produtos'), api('/api/clientes')]); fillProducts(); fillClients(); const categories = await api('/api/categorias'); document.querySelector('#product-category-filter').innerHTML = '<option value="">Todas as categorias</option>' + categories.map((category) => `<option>${escapeHtml(category.nome)}</option>`).join(''); document.querySelector('#category-edit-select').innerHTML = '<option value="">Editar categoria...</option>' + categories.map((category) => `<option value="${category.id}">${escapeHtml(category.nome)}</option>`).join(''); renderAdminProducts(); document.querySelector('#clients-body').innerHTML = clients.map((client) => `<tr><td>${escapeHtml(client.nome)}</td><td>${escapeHtml(client.documento)}</td><td>${escapeHtml(client.telefone)}</td><td>${escapeHtml(client.email)}</td></tr>`).join(''); const company = await api('/api/configuracoes/empresa'); companyFields.forEach((field) => { const input = document.querySelector(`#company-${field}`); if (input) input.value = company?.[field] || ''; }); }
function renderQuotes() { const search = quoteSearchInput.value.trim().toLocaleLowerCase(); const status = quoteStatusFilter.value; const visible = quotes.filter((quote) => (!search || `${quote.numero} ${quote.clienteNome || quote.cliente}`.toLocaleLowerCase().includes(search)) && (!status || quote.status === status)); quotesBody.innerHTML = visible.map((quote) => `<tr><td><strong>${escapeHtml(quote.numero)}</strong></td><td>${escapeHtml(quote.clienteNome || quote.cliente)}</td><td>${quote.items?.length || 0}</td><td><strong>${money(quote.totalGeral || quote.valorFinal)}</strong></td><td><span class="status-badge status-${quote.status.toLocaleLowerCase().replace(/\s/g, '-')}">${escapeHtml(quote.status)}</span></td><td>${formatDate(quote.criadoEm)}</td><td><div class="actions"><button class="action-button" data-quote-action="pdf" data-id="${quote.id}" type="button">PDF</button><button class="action-button delete" data-quote-action="delete" data-id="${quote.id}" type="button">Excluir</button></div></td></tr>`).join(''); quotesEmptyState.classList.toggle('hidden', visible.length !== 0); document.querySelector('#quote-record-badge').textContent = `${quotes.length} ${quotes.length === 1 ? 'registro' : 'registros'}`; }
async function loadQuotes() { const data = await api('/api/orcamentos'); quotes = data; renderQuotes(); }
function quotePayload() { return { clienteId: quoteField('clienteId').value, items: quoteItems, validadeDias: quoteField('validadeDias').value, maoObra: quoteField('maoObra').value, instalacao: quoteField('instalacao').value, deslocamento: quoteField('deslocamento').value, desconto: quoteField('desconto').value, acrescimos: quoteField('acrescimos').value, observacoes: quoteField('observacoes').value, status: quoteField('status').value }; }
function resetQuoteForm() { quoteForm.reset(); quoteItems = []; editingQuoteId = null; quoteField('validadeDias').value = 10; ['maoObra', 'instalacao', 'deslocamento', 'desconto', 'acrescimos'].forEach((field) => { quoteField(field).value = 0; }); document.querySelector('#quote-form-title').textContent = 'Criar orçamento'; document.querySelector('#quote-submit-button').textContent = 'Salvar orçamento'; document.querySelector('#cancel-quote-edit').classList.add('hidden'); document.querySelector('#quote-pdf-button').disabled = true; renderItems(); }
document.querySelector('#item-product').addEventListener('change', () => { const product = products.find((item) => item.id === Number(document.querySelector('#item-product').value)); if (product) document.querySelector('#item-unit').value = product.unidade; });
document.querySelector('#add-item').addEventListener('click', () => { const product = products.find((item) => item.id === Number(document.querySelector('#item-product').value)); const quantity = Number(document.querySelector('#item-quantity').value); const width = Number(document.querySelector('#item-width').value) || 0; const height = Number(document.querySelector('#item-height').value) || 0; if (!product || !quantity) return showMessage('Selecione um produto e informe a quantidade.', 'error'); const area = width * height; quoteItems.push({ produtoId: product.id, descricao: product.nome, categoria: product.categoria, unidade: document.querySelector('#item-unit').value, quantidade, largura: width, altura: height, area, valorUnitario: Number(product.preco), subtotal: (area ? area * quantity : quantity) * Number(product.preco) }); renderItems(); });
document.querySelector('#quote-items-body').addEventListener('click', (event) => { const button = event.target.closest('[data-remove-item]'); if (!button) return; quoteItems.splice(Number(button.dataset.removeItem), 1); renderItems(); });
quoteForm.addEventListener('input', renderItems);
quoteForm.addEventListener('submit', async (event) => { event.preventDefault(); const button = document.querySelector('#quote-submit-button'); button.disabled = true; try { const data = await api(editingQuoteId ? `/api/orcamentos/${editingQuoteId}` : '/api/orcamentos', { method: editingQuoteId ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(quotePayload()) }); await loadQuotes(); resetQuoteForm(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } finally { button.disabled = false; } });
quotesBody.addEventListener('click', async (event) => { const button = event.target.closest('[data-quote-action]'); if (!button) return; const quote = quotes.find((item) => item.id === Number(button.dataset.id)); if (!quote) return; if (button.dataset.quoteAction === 'edit') return beginQuoteEdit(quote); if (button.dataset.quoteAction === 'pdf') window.open(`/api/orcamentos/${quote.id}/pdf`, '_blank'); if (button.dataset.quoteAction === 'delete' && window.confirm(`Excluir o orçamento ${quote.numero}?`)) { try { const data = await api(`/api/orcamentos/${quote.id}`, { method: 'DELETE' }); await loadQuotes(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } } });
quoteSearchInput.addEventListener('input', renderQuotes); quoteStatusFilter.addEventListener('change', renderQuotes); document.querySelector('#cancel-quote-edit').addEventListener('click', resetQuoteForm);
document.querySelector('#client-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const data = await api('/api/clientes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); await loadAdminData(); event.target.reset(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } });
document.querySelector('#category-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const data = await api('/api/categorias', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); event.target.reset(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } });
document.querySelector('#category-edit-button').addEventListener('click', async () => { const select = document.querySelector('#category-edit-select'); if (!select.value) return showMessage('Selecione uma categoria.', 'error'); const name = window.prompt('Novo nome da categoria:', select.options[select.selectedIndex].text); if (!name) return; try { const data = await api(`/api/categorias/${select.value}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nome: name }) }); await loadAdminData(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } });
document.querySelector('#product-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const data = await api('/api/produtos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); await loadAdminData(); event.target.reset(); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } });
document.querySelector('#products-body').addEventListener('click', async (event) => { const button = event.target.closest('[data-product-action]'); if (!button) return; const product = products.find((item) => item.id === Number(button.dataset.id)); if (!product) return; try { if (button.dataset.productAction === 'delete') { if (!window.confirm(`Excluir ${product.nome}?`)) return; await api(`/api/produtos/${product.id}`, { method: 'DELETE' }); } else { const price = window.prompt('Preço em R$:', product.preco); if (price === null) return; const active = button.dataset.productAction === 'toggle' ? !product.ativo : Boolean(product.ativo); await api(`/api/produtos/${product.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...product, preco: price, ativo: active }) }); } await loadAdminData(); showMessage('Produto atualizado com sucesso.'); } catch (error) { showMessage(error.message, 'error'); } });
setupCompanyForm();
setupClientForm();
setupCategoryForm();
setupProductFilters();
document.querySelector('#product-search').addEventListener('input', renderAdminProducts);
document.querySelector('#product-category-filter').addEventListener('change', renderAdminProducts);
document.querySelector('#company-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const data = await api('/api/configuracoes/empresa', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); showMessage(data.message); } catch (error) { showMessage(error.message, 'error'); } });
document.querySelectorAll('.admin-tab').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('.admin-tab').forEach((item) => item.classList.toggle('active', item === tab)); document.querySelectorAll('.admin-view').forEach((view) => view.classList.toggle('hidden', view.id !== `admin-${tab.dataset.adminTab}`)); }));
loadAdminData().then(loadQuotes).catch((error) => showMessage(error.message, 'error'));
function beginQuoteEdit(quote) { editingQuoteId = quote.id; quoteField('clienteId').value = quote.clienteId || ''; quoteField('validadeDias').value = quote.validadeDias || 10; ['maoObra', 'instalacao', 'deslocamento', 'desconto', 'acrescimos'].forEach((field) => { quoteField(field).value = quote[field] || 0; }); quoteField('observacoes').value = quote.observacoes || ''; quoteField('status').value = quote.status; quoteItems = (quote.items || []).map((item) => ({ produtoId: item.produtoId, descricao: item.descricao, categoria: item.categoria, unidade: item.unidade, quantidade: Number(item.quantidade), largura: Number(item.largura), altura: Number(item.altura), area: Number(item.area), valorUnitario: Number(item.valorUnitario), subtotal: Number(item.subtotal) })); document.querySelector('#quote-form-title').textContent = 'Editar orçamento'; document.querySelector('#quote-submit-button').textContent = 'Atualizar orçamento'; document.querySelector('#cancel-quote-edit').classList.remove('hidden'); document.querySelector('#quote-pdf-button').disabled = false; renderItems(); }
quotesBody.addEventListener('dblclick', (event) => { const row = event.target.closest('tr'); if (!row) return; const quote = quotes.find((item) => item.numero === row.querySelector('td')?.textContent.trim()); if (quote) beginQuoteEdit(quote); });
new MutationObserver(() => quotesBody.querySelectorAll('tr').forEach((row) => { if (row.querySelector('[data-quote-action="edit"]')) return; const id = row.querySelector('[data-id]')?.dataset.id; const number = row.querySelector('td')?.textContent.trim(); const quote = quotes.find((item) => item.numero === number); if (quote) row.querySelector('.actions').insertAdjacentHTML('afterbegin', `<button class="action-button" data-quote-action="edit" data-id="${quote.id}" type="button">Editar</button>`); })).observe(quotesBody, { childList: true });
