import { useState } from 'react';
import { Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { Card, Button, Empty, Field, Modal, SectionTitle, Spinner } from '../components/common';
import { deleteClient, getClients, saveClient } from '../services/api';
import { useLoad } from '../hooks/useLoad';

const empty = { nome: '', documento: '', telefone: '', whatsapp: '', email: '', endereco: '', numero: '', complemento: '', bairro: '', cidade: '', estado: '', cep: '' };
export default function Clients({ notify }) { const { data: clients = [], loading, error, reload } = useLoad(() => getClients(), []); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null); const [form, setForm] = useState(empty); const [busy, setBusy] = useState(false); const change = (key, value) => setForm({ ...form, [key]: value }); const submit = async (e) => { e.preventDefault(); setBusy(true); try { const result = await saveClient(editing?.id, form); notify(result.message); setEditing(null); setForm(empty); reload(); } catch (err) { notify(err.message, 'error'); } finally { setBusy(false); } }; const visible = clients.filter((c) => `${c.nome} ${c.documento || ''} ${c.telefone || ''}`.toLowerCase().includes(search.toLowerCase())); const open = (client = null) => { setEditing(client || {}); setForm(client ? { ...empty, ...client } : empty); };
  return <><div className="page-heading"><div><span className="eyebrow">Relacionamento</span><h1>Clientes</h1><p className="muted">Uma visão completa de quem movimenta seu negócio.</p></div><Button icon={Plus} onClick={() => open()}>Novo cliente</Button></div><Card><SectionTitle eyebrow="Base de clientes" title="Todos os clientes"><div className="search"><Search size={17} /><input placeholder="Pesquisar por nome, documento ou telefone" value={search} onChange={(e) => setSearch(e.target.value)} /></div></SectionTitle>{error && <div className="feedback error visible">{error}</div>}{loading ? <div className="loading-inline"><Spinner /></div> : <div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Documento</th><th>Telefone</th><th>Email</th><th>Localização</th><th /></tr></thead><tbody>{visible.map((client) => <tr key={client.id}><td><b>{client.nome}</b><small>{client.whatsapp || 'WhatsApp não informado'}</small></td><td>{client.documento || '-'}</td><td>{client.telefone || '-'}</td><td>{client.email || '-'}</td><td>{[client.cidade, client.estado].filter(Boolean).join(' / ') || '-'}</td><td><div className="actions"><button className="icon-button" onClick={() => open(client)} aria-label="Editar"><Pencil size={16} /></button><button className="icon-button danger" onClick={async () => { if (!confirm(`Excluir ${client.nome}?`)) return; try { const result = await deleteClient(client.id); notify(result.message); reload(); } catch (err) { notify(err.message, 'error'); } }} aria-label="Excluir"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>{!visible.length && <Empty>Nenhum cliente corresponde à sua busca.</Empty>}</div>}</Card>{editing !== null && <Modal title={editing ? 'Editar cliente' : 'Novo cliente'} onClose={() => setEditing(null)}><form className="form-grid" onSubmit={submit}>{Object.keys(empty).map((key) => <Field key={key} label={key === 'nome' ? 'Nome / Razão social' : key}><input required={key === 'nome'} value={form[key]} onChange={(e) => change(key, e.target.value)} /></Field>)}<div className="modal-actions"><Button type="button" variant="ghost" onClick={() => setEditing(null)}>Cancelar</Button><Button type="submit" disabled={busy}>{busy ? 'Salvando...' : 'Salvar cliente'}</Button></div></form></Modal>}</>;
}
