import { useLoad, money } from '../hooks/useLoad';
import { getClients, getProducts, getQuotes } from '../services/api';
import { Card, Empty, SectionTitle, Spinner } from '../components/common';
import { ArrowUpRight, CheckCircle2, CircleDollarSign, FileText, Package, Users } from 'lucide-react';

export default function Dashboard({ setPage }) {
  const { data, loading, error } = useLoad(async () => Promise.all([getQuotes(), getClients(), getProducts(true)]).then(([quotes, clients, products]) => ({ quotes, clients, products })), []);
  if (loading) return <div className="loading-inline"><Spinner />Carregando visão geral...</div>;
  if (error) return <div className="feedback error visible">{error}</div>;
  const quotes = data.quotes; const approved = quotes.filter((q) => q.status === 'Aprovado'); const pending = quotes.filter((q) => !['Aprovado', 'Recusado', 'Cancelado', 'Concluído'].includes(q.status)); const total = quotes.reduce((sum, q) => sum + Number(q.totalGeral || q.valorFinal || 0), 0);
  const cards = [[FileText, 'Orçamentos', quotes.length, 'quotes'], [CheckCircle2, 'Aprovados', approved.length, 'quotes'], [CircleDollarSign, 'Valor em carteira', money(total), 'quotes'], [Users, 'Clientes', data.clients.length, 'clients'], [Package, 'Produtos ativos', data.products.filter((p) => p.ativo).length, 'products']];
  return <><div className="page-heading"><div><span className="eyebrow">Visão geral</span><h1>Bom trabalho. Aqui está o pulso da operação.</h1><p className="muted">Acompanhe oportunidades, clientes e catálogo em um só lugar.</p></div><time>{new Date().toLocaleDateString('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' })}</time></div><div className="metric-grid">{cards.map(([Icon, label, value, target]) => <button className="metric-card" key={label} onClick={() => setPage(target)}><span className="metric-icon"><Icon size={19} /></span><span className="metric-label">{label}</span><strong>{value}</strong><ArrowUpRight size={16} /></button>)}</div><div className="dashboard-grid"><Card><SectionTitle eyebrow="Ritmo comercial" title="Orçamentos recentes" /><div className="mini-list">{quotes.slice(0, 5).map((quote) => <div className="mini-row" key={quote.id}><span><b>{quote.numero}</b><small>{quote.clienteNome || quote.cliente}</small></span><span className="row-right"><b>{money(quote.totalGeral || quote.valorFinal)}</b><small className={`status status-${quote.status.toLowerCase().replaceAll(' ', '-')}`}>{quote.status}</small></span></div>)}{!quotes.length && <Empty>Seus orçamentos aparecerão aqui.</Empty>}</div></Card><Card className="focus-card"><span className="eyebrow">Atenção</span><h2>{pending.length} {pending.length === 1 ? 'orçamento aguarda' : 'orçamentos aguardam'} andamento</h2><p className="muted">Mantenha o funil atualizado para que nenhuma oportunidade fique parada.</p><button className="text-button" onClick={() => setPage('quotes')}>Ver orçamentos <ArrowUpRight size={16} /></button></Card></div></>;
}
